java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  secrets:
    STORAGE_ACCOUNT_NAME:
      disabled: true
    STORAGE_ACCOUNT_KEY:
      disabled: true
    STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:
      disabled: true
  environment:
    # Endpoints
    IDAM_USER_BASE_URI: https://preprod-idamapi.reform.hmcts.net:3511
    IDAM_S2S_BASE_URI: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

    # logging vars & healthcheck
    REFORM_ENVIRONMENT: aat
    PACKAGES_ENVIRONMENT: aat

    STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=AAAAAAAAAAAAAAAA;AccountKey=AAAAAAAAAAAAAAAA;EndpointSuffix=core.windows.net'
    ENABLE_AZURE_STORAGE_CONTAINER: 'false'
    POSTGRES_STORAGE_ENABLED: 'true'

postgresql:
  enabled: true
dm-store:
  blobstorage:
    enabled: false
