---
version: '3'

services:
  dm-store:
    build:
        context: .
    image: hmcts/dm-store:latest
    environment:
        SERVER_PORT: 8080
        SPRING_DATASOURCE_URL: jdbc:postgresql://dm-store-db:5432/evidence
        IDAM_USER_BASE_URI: http://idam-api:8080
        IDAM_S2S_BASE_URI: http://service-auth-provider-api:8080
        STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: "${STORAGEACCOUNT_PRIMARY_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-storage-emulator-azurite:10000/devstoreaccount1}"
        STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME: "${STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:-hmctstestcontainer}"
        BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY_REQUIRED: "${BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY_REQUIRED:-false}"
        BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY: "${BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY:-ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDiQ//gc/G53d9dLCtf123fIYo49gUySuJuxOcw2GtieWTMSy+O7RNtsAIjVf3mCOdDNuN69tZNPEWMdaW8n11s9MwYFahtxDecyn0KIP9MvPsfSMSbxhp/f7kfbdB/H/S5eYea66JTyeJS6uNd76RdHttx0mLO30ZkRcXB25c2SIXhRYsdoeKS5GXHDdNejkQM0S/Ev94x2UunApmYHjWN1XcDhsEsAeF4WHnvYh2XiMn9vHY44AqvbWLlAmCgzaXpz8Xhl0fO7jDKSeReDyuM3UTMaiFFaxuvliGol7aIXq/aVe/miiD2SLxHZ6RxAPW80bhXrzJMTLTCqhCEhzfv someone@somewhere.sometime}"
        ENABLE_AZURE_STORAGE_CONTAINER: "true"
        SPRING_PROFILES_ACTIVE: dev
        # these environment variables are used by java-logging library
        ROOT_APPENDER: JSON_CONSOLE
        JSON_CONSOLE_PRETTY_PRINT: "false"
        REFORM_SERVICE_TYPE: java
        REFORM_SERVICE_NAME: dm-store
        REFORM_TEAM: evidence
        REFORM_ENVIRONMENT: docker
    links:
        - dm-store-db
        - azure-storage-emulator-azurite
    depends_on:
        - dm-store-db
        - azure-storage-emulator-azurite
    ports:
        - $SERVER_PORT:8080

  dm-store-db:
    build:
        context: ./docker/database
    image: hmcts/dm-store-db:latest
    ports:
        - 5432:5432

  azure-storage-emulator-azurite:
    image: arafato/azurite
    ports:
         - 10000:10000
    environment:
        executable: "blob"
    volumes:
        - ccd-docker-azure-blob-data:/opt/azurite/folder

  idam-api:
    image: pactfoundation/pact-stub-server
    command: -p 8080 -f pacts/dm-sidam.json --provider-state-header-name P_STATE
    ports:
        - "4501:8080"
    volumes:
        - ./pacts:/app/pacts

  service-auth-provider-api:
    image: pactfoundation/pact-stub-server
    command: -p 8080 -f pacts/dm-s2s.json --provider-state-header-name P_STATE
    ports:
        - "4502:8080"
    volumes:
        - ./pacts:/app/pacts

volumes:
    pacts:
    ccd-docker-azure-blob-data:
